name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test --colors
